package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private int brandId;
     private String brandName;
     private Set vehicles = new HashSet(0);

    public Brand() {
    }

	
    public Brand(int brandId) {
        this.brandId = brandId;
    }
    public Brand(int brandId, String brandName, Set vehicles) {
       this.brandId = brandId;
       this.brandName = brandName;
       this.vehicles = vehicles;
    }
   
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


