package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private int customerId;
    private String address;
    private String phone;
     private String email;
    private String fullname;

     
    private Set salesOrders = new HashSet(0);

    public Customer(int customerId) {
        this.customerId = customerId;
    }

    public Customer(int customerId, String fullname, Set salesOrders) {
        this.customerId = customerId;
        this.fullname = fullname;
        this.salesOrders = salesOrders;
    }

    public Customer(int customerId, String address, String phone, String email, String fullname) {
        this.customerId = customerId;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.fullname = fullname;
    }

    
    
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
   

    public Customer() {
    }

    
    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public Set getSalesOrders() {
        return this.salesOrders;
    }

    public void setSalesOrders(Set salesOrders) {
        this.salesOrders = salesOrders;
    }

}
