package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrder generated by hbm2java
 */
public class PurchaseOrder  implements java.io.Serializable {


     private int purchaseId;
     private String purchaseDate;
     private Integer status;
     private Set purchaseOrderDetailses = new HashSet(0);

    public PurchaseOrder() {
    }

	
    public PurchaseOrder(int purchaseId) {
        this.purchaseId = purchaseId;
    }
    public PurchaseOrder(int purchaseId, String purchaseDate, Integer status, Set purchaseOrderDetailses) {
       this.purchaseId = purchaseId;
       this.purchaseDate = purchaseDate;
       this.status = status;
       this.purchaseOrderDetailses = purchaseOrderDetailses;
    }
   
    public int getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(int purchaseId) {
        this.purchaseId = purchaseId;
    }
    public String getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getPurchaseOrderDetailses() {
        return this.purchaseOrderDetailses;
    }
    
    public void setPurchaseOrderDetailses(Set purchaseOrderDetailses) {
        this.purchaseOrderDetailses = purchaseOrderDetailses;
    }




}


