package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrderDetails generated by hbm2java
 */
public class PurchaseOrderDetails  implements java.io.Serializable {


     private PurchaseOrderDetailsId id;
     private PurchaseOrder purchaseOrder;
     private Vehicle vehicle;
     private Double purchasePrice;
     private Integer quantity;
     private Set vehicleRegistrations = new HashSet(0);

    public PurchaseOrderDetails() {
    }

	
    public PurchaseOrderDetails(PurchaseOrderDetailsId id, PurchaseOrder purchaseOrder, Vehicle vehicle) {
        this.id = id;
        this.purchaseOrder = purchaseOrder;
        this.vehicle = vehicle;
    }
    public PurchaseOrderDetails(PurchaseOrderDetailsId id, PurchaseOrder purchaseOrder, Vehicle vehicle, Double purchasePrice, Integer quantity, Set vehicleRegistrations) {
       this.id = id;
       this.purchaseOrder = purchaseOrder;
       this.vehicle = vehicle;
       this.purchasePrice = purchasePrice;
       this.quantity = quantity;
       this.vehicleRegistrations = vehicleRegistrations;
    }
   
    public PurchaseOrderDetailsId getId() {
        return this.id;
    }
    
    public void setId(PurchaseOrderDetailsId id) {
        this.id = id;
    }
    public PurchaseOrder getPurchaseOrder() {
        return this.purchaseOrder;
    }
    
    public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
        this.purchaseOrder = purchaseOrder;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Double getPurchasePrice() {
        return this.purchasePrice;
    }
    
    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Set getVehicleRegistrations() {
        return this.vehicleRegistrations;
    }
    
    public void setVehicleRegistrations(Set vehicleRegistrations) {
        this.vehicleRegistrations = vehicleRegistrations;
    }




}


