package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1



/**
 * SalesOrderDetailsId generated by hbm2java
 */
public class SalesOrderDetailsId  implements java.io.Serializable {


     private int registrationId;
     private int salesId;

    public SalesOrderDetailsId() {
    }

    public SalesOrderDetailsId(int registrationId, int salesId) {
       this.registrationId = registrationId;
       this.salesId = salesId;
    }
   
    public int getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(int registrationId) {
        this.registrationId = registrationId;
    }
    public int getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(int salesId) {
        this.salesId = salesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SalesOrderDetailsId) ) return false;
		 SalesOrderDetailsId castOther = ( SalesOrderDetailsId ) other; 
         
		 return (this.getRegistrationId()==castOther.getRegistrationId())
 && (this.getSalesId()==castOther.getSalesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegistrationId();
         result = 37 * result + this.getSalesId();
         return result;
   }   


}


