package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String username;
     private String password;

    public User() {
    }

	
    public User(int userId) {
        this.userId = userId;
    }
    public User(int userId, String username, String password) {
       this.userId = userId;
       this.username = username;
       this.password = password;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


