package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private int vehicleId;
     private Brand brand;
     private String name;
     private String modelNumber;
     private Set purchaseOrderDetailses = new HashSet(0);

    public Vehicle() {
    }

	
    public Vehicle(int vehicleId) {
        this.vehicleId = vehicleId;
    }
    public Vehicle(int vehicleId, Brand brand, String name, String modelNumber, Set purchaseOrderDetailses) {
       this.vehicleId = vehicleId;
       this.brand = brand;
       this.name = name;
       this.modelNumber = modelNumber;
       this.purchaseOrderDetailses = purchaseOrderDetailses;
    }
   
    public int getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(int vehicleId) {
        this.vehicleId = vehicleId;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getModelNumber() {
        return this.modelNumber;
    }
    
    public void setModelNumber(String modelNumber) {
        this.modelNumber = modelNumber;
    }
    public Set getPurchaseOrderDetailses() {
        return this.purchaseOrderDetailses;
    }
    
    public void setPurchaseOrderDetailses(Set purchaseOrderDetailses) {
        this.purchaseOrderDetailses = purchaseOrderDetailses;
    }




}


