package common.bean;
// Generated Mar 14, 2015 11:28:19 PM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * VehicleRegistration generated by hbm2java
 */
public class VehicleRegistration  implements java.io.Serializable {


     private int registrationId;
     private PurchaseOrderDetails purchaseOrderDetails;
     private Double price;
     private String remarks;
     private String type;
     private Set salesOrderDetailses = new HashSet(0);

    public VehicleRegistration() {
    }

	
    public VehicleRegistration(int registrationId) {
        this.registrationId = registrationId;
    }
    public VehicleRegistration(int registrationId, PurchaseOrderDetails purchaseOrderDetails, Double price, String remarks, String type, Set salesOrderDetailses) {
       this.registrationId = registrationId;
       this.purchaseOrderDetails = purchaseOrderDetails;
       this.price = price;
       this.remarks = remarks;
       this.type = type;
       this.salesOrderDetailses = salesOrderDetailses;
    }
   
    public int getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(int registrationId) {
        this.registrationId = registrationId;
    }
    public PurchaseOrderDetails getPurchaseOrderDetails() {
        return this.purchaseOrderDetails;
    }
    
    public void setPurchaseOrderDetails(PurchaseOrderDetails purchaseOrderDetails) {
        this.purchaseOrderDetails = purchaseOrderDetails;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getSalesOrderDetailses() {
        return this.salesOrderDetailses;
    }
    
    public void setSalesOrderDetailses(Set salesOrderDetailses) {
        this.salesOrderDetailses = salesOrderDetailses;
    }




}


